# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml
analyzer:
  exclude:
    - lib/generated_plugin_registrant.dart
    - lib/firebase_options.dart
    - example/lib/firebase_options.dart
  errors:
    # https://github.com/rrousselGit/freezed/issues/488
    invalid_annotation_target: ignore
linter:
  rules:
    specify_nonobvious_property_types: false
