targets:
  $default:
    builders:
      json_serializable:
        options:
          any_map: true
          explicit_to_json: true
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - type=lint
            - implicit_dynamic_parameter
            - implicit_dynamic_type
            - implicit_dynamic_method
            - strict_raw_type
            - unused_field
            - unused_element
